#!/bin/bash

NAME='ALERTS'

APPDIR=${PWD}
BASEDIR=$(dirname "$APPDIR")
VENVDIR=$BASEDIR
PIDFILE=$BASEDIR/run/alertas.pidz:x
USER=www
GROUP=www
NUM_WORKERS=2


source $VENVDIR/bin/activate

export PYTHONPATH=$APPDIR:$PYTHONPATH

# Create the run directory if it doesn't exist
RUNDIR=$(dirname $PIDFILE)
test -d $RUNDIR || mkdir -p $RUNDIR

# Start your unicorn
exec gunicorn -w $NUM_WORKERS run:app -b 0.0.0.0:5000 --name $NAME -p $PIDFILE
